<?php

return [

    'rules' => [
        'accepted' => '01',
        'active_url' => '02',
        'after' => '03',
        'after_or_equal' => '04',
        'alpha' => '05',
        'alpha_dash' => '06',
        'alpha_num' => '07',
        'array' => '08',
        'before' => '09',
        'before_or_equal' => '10',
        'between' => [
            'numeric' => '11',
            'file' => '12',
            'string' => '13',
            'array' => '14',
        ],
        'boolean' => '15',
        'confirmed' => '16',
        'current_password' => '17',
        'date' => '18',
        'date_equals' => '19',
        'date_format' => '20',
        'different' => '21',
        'digits' => '22',
        'digits_between' => '23',
        'dimensions' => '24',
        'distinct' => '25',
        'email' => '26',
        'ends_with' => '27',
        'exists' => '28',
        'file' => '29',
        'filled' => '30',
        'gt' => [
            'numeric' => '31',
            'file' => '32',
            'string' => '33',
            'array' => '34',
        ],
        'gte' => [
            'numeric' => '35',
            'file' => '36',
            'string' => '37',
            'array' => '38',
        ],
        'image' => '39',
        'in' => '40',
        'in_array' => '41',
        'integer' => '42',
        'ip' => '43',
        'ipv4' => '44',
        'ipv6' => '45',
        'json' => '46',
        'lt' => [
            'numeric' => '47',
            'file' => '48',
            'string' => '49',
            'array' => '50',
        ],
        'lte' => [
            'numeric' => '51',
            'file' => '52',
            'string' => '53',
            'array' => '54',
        ],
        'max' => [
            'numeric' => '55',
            'file' => '56',
            'string' => '57',
            'array' => '58',
        ],
        'mimes' => '59',
        'mimetypes' => '60',
        'min' => [
            'numeric' => '61',
            'file' => '62',
            'string' => '63',
            'array' => '64',
        ],
        'multiple_of' => '65',
        'not_in' => '66',
        'not_regex' => '67',
        'numeric' => '68',
        'password' => '69',
        'present' => '70',
        'regex' => '71',
        'required' => '72',
        'required_if' => '73',
        'required_unless' => '74',
        'required_with' => '75',
        'required_with_all' => '76',
        'required_without' => '77',
        'required_without_all' => '78',
        'prohibited' => '79',
        'prohibited_if' => '80',
        'prohibited_unless' => '81',
        'same' => '82',
        'size' => [
            'numeric' => '83',
            'file' => '84',
            'string' => '85',
            'array' => '86',
        ],
        'starts_with' => '87',
        'string' => '88',
        'timezone' => '89',
        'unique' => '90',
        'uploaded' => '91',
        'url' => '92',
        'uuid' => '93',
        'used' => '94',
        'in_month' => '95',
        'after_timestamp' => '96',
        'audio' => '97',
        'document' => '98',
        'array_max_saved' => '99',
        'array_existence' => '100',
        'integer_id' => '101' 
    ],

    'attributes' => [
        'address' => '0101',
        'access_token' => '0102',
        'city' => '0301',
        'device_name' => '0401',
        'description' => '0402',
        'email' => '0501',
        'login' => '1201',
        'name' => '1401',
        'password' => '1601',
        'paginate' => '1602',
        'phone' => '1603',
        'refresh_token' => '1801',
        'surname' => '1901',
        'username' => '2101',
        'zipcode' => '2601'
    ],

];
